[Hit(uuid='0',
     path='/README.md',
     lineno=1,
     depth=1,
     type='documentation',
     name='',
     text='# Toolbar Manager\n'
          '\n'
          'Toolbar Manager for the Space Engineers game.\n'
          '\n'
          'For support please [join the SE Mods '
          'Discord](https://discord.gg/PYPFPGf3Ca).\n'
          '\n'
          'Please consider [supporting my work on '
          'Patreon](https://www.patreon.com/semods).\n'
          '\n'
          '## Features\n'
          '\n'
          'This plugin allows for saving and loading toolbars. For example you '
          'can \n'
          'quickly load a "standard" toolbar into any game, which can greatly '
          'speed\n'
          'up your builds by using toolbar slots you have already memorized.\n'
          '\n'
          'This plugin works for both offline and online multiplayer games '
          'without\n'
          'the need for any server side support. All your save files are '
          'local, \n'
          'nothing is stored on a server.\n'
          '\n'
          '### Toolbars\n'
          '\n'
          'The **G menu** has two new buttons to manage saved toolbars:\n'
          '- Save\n'
          '- Load\n'
          '\n'
          '**Merge** is the same as **Load**, but does not clear slots not '
          'used by the toolbar loaded.\n'
          '\n'
          'Saved toolbars are stored as XML files under: '
          '`%AppData%\\Roaming\\SpaceEngineers\\ToolbarManager`\n'
          '\n'
          'There are subdirectories for each toolbar type. Toolbars within the '
          'same type are compatible,\n'
          'altough they may not have the same amount of slots available.\n'
          '\n'
          'It is possible to save the toolbar from a cockpit and load into a '
          'remote control, for example.\n'
          '\n'
          '### Quick block selection\n'
          '\n'
          'Press the `BACKSLASH` or `PIPE` key (on English keyboard) to open '
          'the quick \n'
          'block search menu. It works the same way as the original menu, but '
          'the search \n'
          'rules are optimized to find blocks primarily by capital letters and '
          'digits:\n'
          '\n'
          '- `AB` **Armor Blocks**\n'
          '- `PB` **Programmable Block**\n'
          '- `SK` **Survival Kit**\n'
          '- `AT` **Atmospheric Thrusters**\n'
          '- `LHT` **Large Hydrogen Thrusters**\n'
          '- `211` **All 2x1x1 armor blocks**\n'
          '\n'
          'Adding the subsequent lower case letters after an upper case one '
          'allows \n'
          'for narrowing down in case of ambiguity:\n'
          '\n'
          '- `PH` **Parachute Hatch** and **Point Hand**\n'
          '- `PHat` **Parachute Hatch** only\n'
          '\n'
          'The order of characters must match exactly. Lower case characters '
          'and\n'
          'space are skipped after a matching upper chase character or '
          'digit. \n'
          '\n'
          'Separating multiple search patterns by space is not supported, '
          'currently.\n'
          '\n'
          '### Planned features\n'
          '- Restricting the load/merge operations to certain toolbar pages\n'
          '- Multiplying the available toolbar pages using new hotkeys and '
          'saved toolbars\n'
          '- Moving and swapping toolbar items using mouse drag&drop\n'
          '- Moving toolbar items between toolbar pages\n'
          '- Swapping toolbar pages\n'
          '\n'
          'Please join the Discord (see below) and tell me which one you would '
          'use, \n'
          'so they can be fast-tracked.  \n'
          '\n'
          '## Installation\n'
          '1. Exit from Space Engineers\n'
          '2. Install the [Plugin '
          'Loader](https://steamcommunity.com/sharedfiles/filedetails/?id=2407984968)\n'
          '3. Start Space Engineers\n'
          '4. Open the Plugins menu (should be in the Main Menu)\n'
          '5. Enable the Toolbar Manager plugin\n'
          '6. Save and let the game restart\n'
          '\n'
          'After enabling the plugin it will be active for all single- and '
          'multiplayer worlds.\n'
          '\n'
          '*Enjoy!*\n'
          '\n'
          '## Want to know more?\n'
          '- [SE Mods Discord](https://discord.gg/PYPFPGf3Ca)\n'
          '- [Plugin Loader Discord](https://discord.gg/6ETGRU3CzR)\n'
          '- [YouTube '
          'Channel](https://www.youtube.com/channel/UCc5ar3cW9qoOgdBb1FM_rxQ)\n'
          '- [Source '
          'code](https://github.com/viktor-ferenczi/toolbar-manager)\n'
          '- [Bug reports](https://discord.gg/x3Z8Ug5YkQ)\n'
          '\n'
          '## Credits\n'
          '\n'
          '### Patreon Supporters\n'
          '\n'
          '#### Admiral level\n'
          '- BetaMark\n'
          '- Mordith - Guardians SE\n'
          '- Robot10\n'
          '- Casinost\n'
          '- wafoxxx\n'
          '\n'
          '#### Captain level\n'
          '- Diggz\n'
          '- lazul\n'
          '- jiringgot\n'
          '- Kam Solastor\n'
          '- NeonDrip\n'
          '- NeVaR\n'
          '- opesoorry\n'
          '- NeVaR\n'
          '- Jimbo\n'
          '- Lotan\n'
          '\n'
          '#### Testers\n'
          '- Avaness\n'
          '- ...\n'
          '\n'
          '### Creators\n'
          '- avaness - Plugin Loader, Racing Display\n'
          '- Mordith - Guardians SE\n'
          '- Mike Dude - Guardians SE\n'
          '- SwiftyTech - Stargate Dimensions\n'
          '- Fred XVI - Racing maps\n'
          '- Kamikaze - M&M mod\n'
          '- LTP\n'
          '\n'
          '**Thank you very much for all your support and hard work on '
          'testing!**',
     tokens=940,
     score=1.0)]