[Hit(uuid='0',
     path='/README.md',
     lineno=1,
     depth=1,
     type='documentation',
     name='',
     text='# C++ Programming\n'
          '\n'
          '\n'
          '## Contents\n'
          '- [Tips](#keep-these-tips-in-mind-while-learning-programming)\n'
          '- [Computer Science Basics](#computer-science-basics)\n'
          '- [Learning Resources](#learning-resources)\n'
          '- [Problem Solving](#problem-solving)\n'
          '- [Projects Ideas](#projects-ideas)\n'
          '\n'
          '\n'
          '## Keep These Tips in Mind While Learning Programming\n'
          '```\n'
          '1. Learn and code every day, consistency is important.\n'
          '2. Write it down - plan your code before you start coding and '
          'understand the input to your program and the output from your '
          'code.\n'
          '3. Learn to debug your code - look at the code line by line to see '
          'how it works.\n'
          '4. Surround yourself with other people who are learning. Teach each '
          'other.\n'
          '5. Learn taking notes.\n'
          '6. Build something, anything. For example, simple calculator, or '
          'program to save and read data from TXT files.\n'
          '7. Focus on 1 thing! Take small steps, but every day, consistency '
          'is very important again.\n'
          '8. Learn to ask GOOD questions to others:\n'
          '  - G: Give context on what you are trying to do, clearly '
          'describing the problem.\n'
          '  - O: Outline the things you have already tried to fix the issue.\n'
          '  - O: Offer your best guess as to what the problem might be. It '
          "helps the person who is helping you not only know what you're "
          "thinking, but also know that you've thought of something yourself.\n"
          "  - D: Demonstrate what's going on. Include the code, the tracing "
          'error message, and an explanation of the steps you followed that '
          "resulted in the error. That way, the person helping doesn't have to "
          'try to recreate the problem.\n'
          '```\n'
          '\n'
          '\n'
          '## Computer Science Basics\n'
          '- [Harvard '
          'CS50](https://youtube.com/playlist?list=PLhQjrBD2T383f9scHRNYJkior2VvYjpSL) '
          '- Scratch, C, Arrays, Algorithms, Memory, Data structures, Python, '
          'SQL, HTML, CSS, JavaScript, Flask\n'
          '- `Optional` [Crash Course Computer '
          'Science](https://www.youtube.com/playlist?list=PL8dPuuaLjXtNlUrzyH5r6jN9ulIgZBpdo)\n'
          '- [Computer Science for '
          'Everyone](https://www.youtube.com/playlist?list=PLrC-HcVNfULbGKkhJSgfqvqmaFAZvfHes) \n'
          '\n'
          '## Learning Resources\n'
          '- EN [C++ for beginners — '
          'CodeBeauty](https://www.youtube.com/playlist?list=PL43pGnjiVwgQHLPnuH9ch-LhZdwckM8Tq)\n'
          '- EN [C++ Programming Tutorial — '
          'thenewboston](https://www.youtube.com/playlist?list=PLAE85DE8440AA6B83)\n'
          '- EN [C++ by The '
          'Cherno](https://www.youtube.com/watch?v=18c3MTX0PK0&list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb)\n'
          '- EN [C++ by '
          'freeCodeCamp.org](https://www.youtube.com/watch?v=vLnPwxZdW4Y)\n'
          '- RU [C++ by Denis '
          'Markov](https://www.youtube.com/playlist?list=PLbmlzoDQrXVFC13GjpPrJxl6mzTiX65gs)\n'
          '- RU [C++ Уроки - Гоша '
          'Дударь](https://www.youtube.com/watch?v=qSHP98i9mDU&list=PL0lO_mIqDDFXNfqIL9PHQM7Wg_kOtDZsW)\n'
          '- To read:\n'
          '  - [cplusplus.com](https://cplusplus.com/doc/tutorial/)\n'
          '  - [w3schools.com](https://www.w3schools.com/cpp/default.asp) \n'
          '  - '
          '[tutorialspoint.com](https://www.tutorialspoint.com/cplusplus/index.htm)\n'
          '  - '
          '[GeegsForGeeks.org](https://www.geeksforgeeks.org/c-plus-plus/):\n'
          '\n'
          '## Problem Solving\n'
          '```\n'
          '1. C++ Program to print "Hello, World!"\n'
          '2. C++ Program to Print an Integer (Entered by the User)\n'
          '3. C++ Program to Add Two Integers\n'
          '4. C++ Program to Multiply two Floating Point Numbers\n'
          '5. C++ Program to Find ASCII Value of a Character\n'
          '6. C++ Program to Compute Quotient and Remainder\n'
          '7. C++ Program to Find the Size of int, float, double and char\n'
          '8. C++ Program to Demonstrate the Working of Keyword long\n'
          '9. C++ Program to Swap Two Numbers\n'
          '10. C++ Program to Check Whether a Number is Even or Odd\n'
          '11. C++ Program to Check Whether a Character is Vowel or Consonant\n'
          '12. C++ Program to Find the Largest Number Among Three Numbers\n'
          '13. C++ Program to Find all Roots of a Quadratic equation\n'
          '14. C++ Program to Check Leap Year\n'
          '15. C++ Program to Check Whether a Number is Positive or Negative\n'
          '16. C++ Program to Check Whether a Character is an Alphabet or not\n'
          '17. C++ Program to Calculate the Sum of Natural Numbers\n'
          '18. C++ Program to Find Factorial of a Number\n'
          '19. C++ Program to Generate Multiplication Table\n'
          '20. C++ Program to Display Fibonacci Sequence\n'
          '21. C++ Program to Find GCD of two Numbers\n'
          '22. C++ Program to Find LCM of two Numbers\n'
          '23. C++ Program to Display Characters from A to Z Using Loop\n'
          '24. C++ Program to Count Number of Digits in an Integer\n'
          '25. C++ Program to Reverse a Number\n'
          '26. C++ Program to Calculate the Power of a Number\n'
          '27. C++ Program to Check Whether a Number is Palindrome or Not\n'
          '28. C++ Program to Check Whether a Number is Prime or Not\n'
          '29. C++ Program to Display Prime Numbers Between Two Intervals\n'
          '30. C++ Program to Check Armstrong Number\n'
          '31. C++ Program to Display Armstrong Number Between Two Intervals\n'
          '32. C++ Program to Display Factors of a Number\n'
          '33. C++ Programming Code To Create Pyramid and Structure\n'
          '34. C++ Program to Make a Simple Calculator Using switch...case\n'
          '35. C++ Program to Display Prime Numbers Between Intervals Using '
          'Function\n'
          '36. C++ Program to Check Prime or Armstrong Number Using '
          'User-defined Function\n'
          '37. C++ Program to Check Whether a Number can be Expressed as Sum '
          'of Two Prime Numbers\n'
          '38. C++ Program to Find the Sum of Natural Numbers using Recursion\n'
          '39. C++ Program to Find Factorial of a Number Using Recursion\n'
          '40. C++ Program to Find G.C.D Using Recursion\n'
          '41. C++ Program to Convert Binary Number to Decimal and vice-versa\n'
          '42. C++ Program to Convert Octal Number to Decimal and vice-versa\n'
          '43. C++ Program to Convert Binary Number to Octal and vice-versa\n'
          '44. C++ Program to Reverse a Sentence Using Recursion\n'
          '45. C++ Program to calculate the power using recursion\n'
          '46. C++ Program to Calculate Average Using Arrays\n'
          '47. C++ Program to Find Largest Element of an Array\n'
          '48. C++ Program to Calculate Standard Deviation\n'
          '49. C++ Program to Add Two Matrix Using Multi-dimensional Arrays\n'
          '50. C++ Program to Multiply to Matrix Using Multi-dimensional '
          'Arrays\n'
          '51. C++ Program to Find Transpose of a Matrix\n'
          '52. C++ Program to Multiply two Matrices by Passing Matrix to a '
          'Function\n'
          '53. C++ Program to Access Elements of an Array Using Pointer\n'
          '54. C++ Program Swap Numbers in Cyclic Order Using Call by '
          'Reference\n'
          '55. C++ Program to Find Largest Number Using Dynamic Memory '
          'Allocation\n'
          '56. C++ Program to Find the Frequency of Characters in a String\n'
          '57. C++ Program to count the number of vowels, consonants and so '
          'on\n'
          '58. C++ Program to Remove all Characters in a String Except '
          'Alphabet\n'
          '59. C++ Program to Find the Length of a String\n'
          '60. C++ Program to Concatenate Two Strings\n'
          '61. C++ Program to Copy String Without Using strcpy()\n'
          '62. C++ Program to Sort Elements in Lexicographical Order '
          '(Dictionary Order)\n'
          '63. C++ Program to Store Information(name, roll and marks) of a '
          'Student Using Structure\n'
          '64. C++ Program to Add Two Distances (in inch-feet) System Using '
          'Structures\n'
          '65. C++ Program to Add Two Complex Numbers by Passing Structure to '
          'a Function\n'
          '66. C++ Program to Calculate Difference Between Two Time Periods\n'
          '67. C++ Program to Store Information of Students Using Structure\n'
          '68. C++ Program to Store Information Using Structures with '
          'Dynamically Memory Allocation\n'
          '69. C++ Program to Write a Sentence to a File\n'
          '70. C++ Program to Read a Line From a File and Display it\n'
          '71. C++ Program to Display its own Source Code as Output\n'
          '72. C++ Programming Code To Create Pyramid and Pattern\n'
          '```\n'
          '\n',
     tokens=1891,
     score=1.0)]