from model.fragment import Fragment

# Parser: MarkdownParser

f0 = Fragment(uuid='TEST-00',
         path='Example.md',
         lineno=1,
         depth=1,
         type='documentation',
         name='',
         text='# Markdown Syntax Examples\n\nThis Markdown document showcases various Markdown syntax elements.\n\n')

f1 = Fragment(uuid='TEST-01',
         path='Example.md',
         lineno=5,
         depth=1,
         type='documentation',
         name='',
         text='## Headings\n'
              '\n'
              'This section demonstrates different levels of headings in Markdown.\n'
              '\n'
              '# Heading 1\n'
              'This is a level 1 heading.\n'
              '\n')

f2 = Fragment(uuid='TEST-02',
         path='Example.md',
         lineno=12,
         depth=1,
         type='documentation',
         name='',
         text='## Heading 2\nThis is a level 2 heading.\n\n### Heading 3\nThis is a level 3 heading.\n\n')

f3 = Fragment(uuid='TEST-03',
         path='Example.md',
         lineno=18,
         depth=1,
         type='documentation',
         name='',
         text='## Emphasis\n'
              '\n'
              'This section demonstrates how to apply emphasis to text.\n'
              '\n'
              '*Italic text*\n'
              'This text is in italic.\n'
              '\n'
              '**Bold text**\n'
              'This text is in bold.\n'
              '\n'
              '***Bold and italic text***\n'
              'This text is both bold and italic.\n'
              '\n')

f4 = Fragment(uuid='TEST-04',
         path='Example.md',
         lineno=31,
         depth=1,
         type='documentation',
         name='',
         text='## Lists\n'
              '\n'
              'This section demonstrates ordered and unordered lists.\n'
              '\n'
              '### Ordered List\n'
              '\n'
              '1. Item 1\n'
              '2. Item 2\n'
              '3. Item 3\n'
              '\n'
              '### Unordered List\n'
              '\n'
              '- Item A\n'
              '- Item B\n'
              '- Item C\n'
              '\n')

f5 = Fragment(uuid='TEST-05',
         path='Example.md',
         lineno=47,
         depth=1,
         type='documentation',
         name='',
         text='## Links\n'
              '\n'
              'This section demonstrates creating links in Markdown.\n'
              '\n'
              "[Visit OpenAI's website](https://openai.com)\n"
              "Click the link to visit OpenAI's website.\n"
              '\n')

f6 = Fragment(uuid='TEST-06',
         path='Example.md',
         lineno=54,
         depth=1,
         type='documentation',
         name='',
         text='## Images\n'
              '\n'
              'This section demonstrates adding images to a Markdown document.\n'
              '\n'
              '![Markdown Logo](https://upload.wikimedia.org/wikipedia/commons/4/48/Markdown-mark.svg)\n'
              'The above image shows the Markdown logo.\n'
              '\n')

f7 = Fragment(uuid='TEST-07',
         path='Example.md',
         lineno=61,
         depth=1,
         type='documentation',
         name='',
         text='## Blockquotes\n'
              '\n'
              'This section demonstrates blockquotes in Markdown.\n'
              '\n'
              '> "Be yourself; everyone else is already taken." - Oscar Wilde\n'
              'This quote is attributed to Oscar Wilde.\n'
              '\n')

f8 = Fragment(uuid='TEST-08',
         path='Example.md',
         lineno=68,
         depth=1,
         type='documentation',
         name='',
         text='## Code\n'
              '\n'
              'This section demonstrates adding code blocks in Markdown.\n'
              '\n'
              '```python\n'
              'def greet(name):\n'
              '    print(f"Hello, {name}!")\n'
              '```\n'
              '\n'
              'After the code block.\n'
              '\n'
              'Examples are generated by ChatGPT-3.5 Turbo.\n')

f9 = Fragment(uuid='TEST-09',
         path='Example.md',
         lineno=1,
         depth=0,
         type='summary',
         name='',
         text='# Markdown Syntax Examples\n'
              '## Headings\n'
              '## Heading 2\n'
              '## Emphasis\n'
              '## Lists\n'
              '## Links\n'
              '## Images\n'
              '## Blockquotes\n'
              '## Code\n')

