name: Deployment to staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Stop server and rename folders
      run: |
        ssh plugin@plugin.askyourcode.ai "rm -rf ~/bin.old; rm -rf ~/src.old; bash ~/bin/stop.sh; mv ~/bin ~/bin.old; mv ~/src ~/src.old"

    - name: Deploy to staging
      run: |
        scp -r bin/ staging@plugin.askyourcode.ai:~/
        scp -r src/ staging@plugin.askyourcode.ai:~/

    - name: Create log folder if it doesn't exist
      run: |
        ssh plugin@plugin.askyourcode.ai "mkdir -p ~/log"

    - name: Restart server and remove old folders
      run: |
        ssh plugin@plugin.askyourcode.ai "bash ~/bin/start.sh"
